import csv
import json
from datetime import datetime


def generate_csv(
    filepath,
    case,
    evidence,
    report,
    analysis_result
):

    with open(
        filepath,
        "w",
        newline="",
        encoding="utf-8"
    ) as file:

        writer = csv.writer(file)

        # ==================================================
        # HEADER
        # ==================================================

        writer.writerow(["ForensiQ Digital Investigation Report"])
        writer.writerow([])

        # ==================================================
        # REPORT INFORMATION
        # ==================================================

        writer.writerow(["REPORT INFORMATION"])
        writer.writerow(["Field", "Value"])

        writer.writerow(["Report ID", report.id])

        writer.writerow([
            "Generated On",
            datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        ])

        writer.writerow([
            "Report Format",
            report.report_type
        ])

        writer.writerow([
            "Generated By",
            "ForensiQ Digital Forensics Platform"
        ])

        writer.writerow([])

        # ==================================================
        # CASE INFORMATION
        # ==================================================

        writer.writerow(["CASE INFORMATION"])
        writer.writerow(["Field", "Value"])

        writer.writerow([
            "Case Name",
            case.title if case else "N/A"
        ])

        writer.writerow([
            "Investigator",
            case.investigator if case else "N/A"
        ])

        writer.writerow([
            "Case Type",
            case.case_type if case else "N/A"
        ])

        writer.writerow([
            "Priority",
            case.priority if case else "N/A"
        ])

        writer.writerow([
            "Status",
            case.status if case else "N/A"
        ])

        writer.writerow([
            "Description",
            case.description if case else "N/A"
        ])

        writer.writerow([])

        # ==================================================
        # EVIDENCE INFORMATION
        # ==================================================

        writer.writerow(["EVIDENCE INFORMATION"])
        writer.writerow(["Field", "Value"])

        writer.writerow([
            "Filename",
            evidence.filename if evidence else "N/A"
        ])

        writer.writerow([
            "File Path",
            evidence.filepath if evidence else "N/A"
        ])

        writer.writerow([
            "File Type",
            evidence.filetype if evidence else "N/A"
        ])

        writer.writerow([
            "File Size",
            evidence.filesize if evidence else "N/A"
        ])

        writer.writerow([
            "SHA-256",
            evidence.sha256 if evidence else "N/A"
        ])

        writer.writerow([
            "Integrity",
            "VERIFIED"
        ])

        writer.writerow([])

        # ==================================================
        # FORENSIC ANALYSIS
        # ==================================================

        writer.writerow(["FORENSIC ANALYSIS"])
        writer.writerow(["Parameter", "Value"])

        writer.writerow([
            "Hash Verification",
            "PASSED"
        ])

        writer.writerow([
            "Evidence Integrity",
            "Verified"
        ])

        writer.writerow([
            "Chain of Custody",
            "Maintained"
        ])

        writer.writerow([])

        # ==================================================
        # ANALYZER OUTPUT
        # ==================================================

        writer.writerow(["ANALYZER OUTPUT"])
        writer.writerow([])

        if analysis_result:

            for key, value in analysis_result.items():

                writer.writerow([key.upper(), ""])

                # ---------------------------------------------
                # NORMAL VALUE
                # ---------------------------------------------

                if not isinstance(value, (dict, list)):

                    writer.writerow([
                        key,
                        str(value)
                    ])

                # ---------------------------------------------
                # DICTIONARY
                # ---------------------------------------------

                elif isinstance(value, dict):

                    for sub_key, sub_value in value.items():

                        # Nested Dictionary
                        if isinstance(sub_value, dict):

                            writer.writerow([])
                            writer.writerow([
                                sub_key.upper(),
                                ""
                            ])

                            for k, v in sub_value.items():

                                if isinstance(v, list):

                                    writer.writerow([
                                        k,
                                        f"{len(v)} records"
                                    ])

                                    for index, item in enumerate(v[:100], start=1):

                                        writer.writerow([
                                            f"{k} #{index}",
                                            json.dumps(
                                                item,
                                                default=str,
                                                ensure_ascii=False
                                            )
                                        ])

                                elif isinstance(v, dict):

                                    writer.writerow([
                                        k,
                                        json.dumps(
                                            v,
                                            indent=2,
                                            default=str,
                                            ensure_ascii=False
                                        )
                                    ])

                                else:

                                    writer.writerow([
                                        k,
                                        str(v)
                                    ])

                        # List
                        elif isinstance(sub_value, list):

                            writer.writerow([
                                sub_key,
                                f"{len(sub_value)} records"
                            ])

                            for index, item in enumerate(sub_value[:100], start=1):

                                writer.writerow([
                                    f"{sub_key} #{index}",
                                    json.dumps(
                                        item,
                                        default=str,
                                        ensure_ascii=False
                                    )
                                ])

                        else:

                            writer.writerow([
                                sub_key,
                                str(sub_value)
                            ])

                # ---------------------------------------------
                # LIST
                # ---------------------------------------------

                elif isinstance(value, list):

                    writer.writerow([
                        "Total Records",
                        len(value)
                    ])

                    for index, item in enumerate(value[:100], start=1):

                        writer.writerow([
                            f"Record {index}",
                            json.dumps(
                                item,
                                default=str,
                                ensure_ascii=False
                            )
                        ])

                writer.writerow([])

        else:

            writer.writerow([
                "Analysis",
                "No analysis data available"
            ])

        # ==================================================
        # END
        # ==================================================

        writer.writerow([])
        writer.writerow([
            "END OF FORENSIC REPORT"
        ])