from datetime import datetime
import json


def generate_html(
    filepath,
    case,
    evidence,
    report,
    analysis_result
):

    if analysis_result:

        analysis_html = f"""
<div class="code-block">
<pre>{json.dumps(
    analysis_result,
    indent=4,
    default=str,
    ensure_ascii=False
)}</pre>
</div>
"""

    else:

        analysis_html = """
<p>No forensic analysis available.</p>
"""



    html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>ForensiQ Report</title>

<style>

body{{
    font-family:Segoe UI,Arial,sans-serif;
    background:#0f172a;
    color:#f8fafc;
    margin:0;
    padding:40px;
}}

.container{{
    max-width:1200px;
    margin:auto;
}}

.header{{
    text-align:center;
    margin-bottom:40px;
}}

.header h1{{
    color:#06b6d4;
    margin-bottom:5px;
}}

.badge{{
    display:inline-block;
    padding:8px 16px;
    background:#059669;
    border-radius:20px;
    font-weight:bold;
}}

.section{{
    margin-top:40px;
}}

.section h2{{
    color:#38bdf8;
    border-bottom:2px solid #334155;
    padding-bottom:8px;
}}

table{{
    width:100%;
    border-collapse:collapse;
    margin-top:15px;
}}

th{{
    background:#1e293b;
}}

th,td{{
    border:1px solid #334155;
    padding:12px;
    text-align:left;
    vertical-align:top;
    word-break:break-word;
}}

.code-block{{
    background:#020617;
    border:1px solid #334155;
    border-radius:10px;
    padding:20px;
    overflow:auto;
}}

pre{{
    margin:0;
    color:#22c55e;
    white-space:pre-wrap;
    word-break:break-word;
}}

.summary{{
    background:#1e293b;
    border-left:5px solid #06b6d4;
    padding:20px;
    border-radius:8px;
    line-height:1.7;
}}

.footer{{
    margin-top:60px;
    text-align:center;
    color:#94a3b8;
    font-size:14px;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>ForensiQ Digital Investigation Report</h1>

<div class="badge">
Evidence Integrity Verified
</div>

</div>



<div class="section">

<h2>Executive Summary</h2>

<div class="summary">

Evidence acquisition completed successfully.<br>

SHA-256 integrity verification passed.<br>

Chain of custody maintained.<br>

Digital forensic analysis completed successfully.

</div>

</div>



<div class="section">

<h2>Case Information</h2>

<table>

<tr>
<th>Field</th>
<th>Value</th>
</tr>

<tr>
<td>Case Name</td>
<td>{case.title if case else "N/A"}</td>
</tr>

<tr>
<td>Investigator</td>
<td>{case.investigator if case else "N/A"}</td>
</tr>

<tr>
<td>Case Type</td>
<td>{case.case_type if case else "N/A"}</td>
</tr>

<tr>
<td>Priority</td>
<td>{case.priority if case else "N/A"}</td>
</tr>

<tr>
<td>Status</td>
<td>{case.status if case else "N/A"}</td>
</tr>

<tr>
<td>Description</td>
<td>{case.description if case else "N/A"}</td>
</tr>

</table>

</div>



<div class="section">

<h2>Evidence Information</h2>

<table>

<tr>
<th>Field</th>
<th>Value</th>
</tr>

<tr>
<td>Filename</td>
<td>{evidence.filename if evidence else "N/A"}</td>
</tr>

<tr>
<td>File Type</td>
<td>{evidence.filetype if evidence else "N/A"}</td>
</tr>

<tr>
<td>File Size</td>
<td>{evidence.filesize if evidence else "N/A"} Bytes</td>
</tr>

<tr>
<td>SHA-256</td>
<td>{evidence.sha256 if evidence else "N/A"}</td>
</tr>

<tr>
<td>Integrity</td>
<td>Verified</td>
</tr>

</table>

</div>



<div class="section">

<h2>Forensic Analysis Result</h2>

{analysis_html}

</div>



<div class="section">

<h2>Report Information</h2>

<table>

<tr>
<th>Field</th>
<th>Value</th>
</tr>

<tr>
<td>Report ID</td>
<td>{report.id}</td>
</tr>

<tr>
<td>Report Format</td>
<td>{report.report_type}</td>
</tr>

<tr>
<td>Generated By</td>
<td>ForensiQ Digital Forensics Platform</td>
</tr>

<tr>
<td>Generated On</td>
<td>{datetime.now().strftime("%d-%m-%Y %H:%M:%S")}</td>
</tr>

</table>

</div>



<div class="footer">

ForensiQ Digital Forensics Platform<br>

© {datetime.now().year} All Rights Reserved

</div>

</div>

</body>

</html>
"""

    with open(
        filepath,
        "w",
        encoding="utf-8"
    ) as file:
        file.write(html)