import json
from datetime import datetime


def generate_json(
    filepath,
    case,
    evidence,
    report,
    analysis_result
):

    report_data = {

        "report": {

            "report_id": report.id,

            "generated_on": datetime.now().strftime(
                "%d-%m-%Y %H:%M:%S"
            ),

            "generated_by": "ForensiQ Digital Forensics Platform",

            "report_format": report.report_type,

            "version": "1.0"

        },



        "case_information": {

            "case_name":
                case.title if case else None,

            "investigator":
                case.investigator if case else None,

            "case_type":
                case.case_type if case else None,

            "priority":
                case.priority if case else None,

            "status":
                case.status if case else None,

            "description":
                case.description if case else None

        },



        "evidence_information": {

            "filename":
                evidence.filename if evidence else None,

            "filepath":
                evidence.filepath if evidence else None,

            "filetype":
                evidence.filetype if evidence else None,

            "filesize":
                evidence.filesize if evidence else None,

            "sha256":
                evidence.sha256 if evidence else None,

            "status":
                evidence.status if evidence else None

        },



        "forensic_summary": {

            "integrity_check": "PASSED",

            "hash_verified": True,

            "chain_of_custody": "Maintained",

            "tampering_detected": False,

            "analysis_status": "Completed"

        },



        "analysis_result":
            analysis_result if analysis_result else {},



        "footer": {

            "tool": "ForensiQ",

            "copyright":
                "Generated by ForensiQ Digital Forensics Platform"

        }

    }



    with open(
        filepath,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(

            report_data,

            file,

            indent=4,

            ensure_ascii=False,

            default=str

        )