from fastapi import APIRouter, Depends
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.database.database import SessionLocal
from app.models.report import Report
from app.models.case import Case
from app.models.evidence import Evidence

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet

import os
from datetime import datetime



router = APIRouter(
    prefix="/reports",
    tags=["Reports"]
)



def get_db():

    db = SessionLocal()

    try:
        yield db

    finally:
        db.close()



REPORT_FOLDER = "uploads/reports"

os.makedirs(
    REPORT_FOLDER,
    exist_ok=True
)





# Get Reports

@router.get("/")
def get_reports(
    db: Session = Depends(get_db)
):

    return db.query(Report).all()







# Create Professional Report

@router.post("/")
def create_report(
    data: dict,
    db: Session = Depends(get_db)
):


    case_name = data.get(
        "case_name",
        "Unknown Case"
    )


    evidence_name = data.get(
        "evidence_name",
        "Unknown Evidence"
    )



    # Find case

    case = (
        db.query(Case)
        .filter(
            Case.title == case_name
        )
        .first()
    )



    # Find evidence

    evidence = (
        db.query(Evidence)
        .filter(
            Evidence.filename == evidence_name
        )
        .first()
    )



    report = Report(

        case_name=case_name,

        evidence_name=evidence_name,

        report_type=data.get(
            "report_type",
            "PDF"
        ),

        status="Generated"

    )



    db.add(report)

    db.commit()

    db.refresh(report)




    filename = (
        f"ForensiQ_Report_{report.id}.pdf"
    )


    filepath = os.path.join(
        REPORT_FOLDER,
        filename
    )




    doc = SimpleDocTemplate(
        filepath
    )



    styles = getSampleStyleSheet()


    content = []




    content.append(

        Paragraph(
            "ForensiQ Digital Forensics Investigation Report",
            styles["Title"]
        )

    )


    content.append(
        Spacer(1,20)
    )





    # Case Section


    content.append(

        Paragraph(
            "CASE INFORMATION",
            styles["Heading2"]
        )

    )


    case_data = [

        ["Case Name", case_name],

        [
            "Investigator",
            case.investigator
            if case
            else "N/A"
        ],

        [
            "Case Type",
            case.case_type
            if case
            else "N/A"
        ],


        [
            "Priority",
            case.priority
            if case
            else "N/A"
        ],


        [
            "Status",
            case.status
            if case
            else "N/A"
        ],

    ]



    table = Table(case_data)


    table.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),0.5,None)

        ])

    )


    content.append(table)



    content.append(
        Spacer(1,20)
    )







    # Evidence Section


    content.append(

        Paragraph(
            "EVIDENCE INFORMATION",
            styles["Heading2"]
        )

    )



    evidence_data = [


        [
            "File Name",
            evidence.filename
            if evidence
            else evidence_name
        ],


        [
            "File Type",
            evidence.filetype
            if evidence
            else "N/A"
        ],


        [
            "File Size",
            evidence.filesize
            if evidence
            else "N/A"
        ],


        [
            "SHA-256",
            evidence.sha256
            if evidence
            else "N/A"
        ],


        [
            "Integrity Status",
            "VERIFIED"
        ]


    ]



    table2 = Table(
        evidence_data
    )


    table2.setStyle(

        TableStyle([

            ("GRID",(0,0),(-1,-1),0.5,None)

        ])

    )



    content.append(table2)



    content.append(
        Spacer(1,20)
    )






    # Footer


    content.append(

        Paragraph(

            f"Generated By : ForensiQ System<br/>"
            f"Generated On : {datetime.now()}",

            styles["Normal"]

        )

    )



    doc.build(content)





    report.file_path = filepath


    db.commit()

    db.refresh(report)



    return report







# View PDF

@router.get("/view/{report_id}")
def view_report(
    report_id:int,
    db:Session=Depends(get_db)
):


    report = (

        db.query(Report)

        .filter(
            Report.id == report_id
        )

        .first()

    )



    if not report:

        return {
            "error":"Report not found"
        }



    return FileResponse(

        report.file_path,

        media_type="application/pdf"

    )







# Download PDF

@router.get("/download/{report_id}")
def download_report(
    report_id:int,
    db:Session=Depends(get_db)
):


    report = (

        db.query(Report)

        .filter(
            Report.id == report_id
        )

        .first()

    )


    return FileResponse(

        report.file_path,

        media_type="application/pdf",

        filename=os.path.basename(
            report.file_path
        )

    )






# Delete Report

@router.delete("/{report_id}")
def delete_report(
    report_id:int,
    db:Session=Depends(get_db)
):


    report = (

        db.query(Report)

        .filter(
            Report.id == report_id
        )

        .first()

    )



    if report.file_path and os.path.exists(
        report.file_path
    ):

        os.remove(
            report.file_path
        )



    db.delete(report)

    db.commit()



    return {
        "message":"Report deleted"
    }